In [2]:
%matplotlib inline
import numpy as np
from sklearn.tree import DecisionTreeClassifier
import pandas

data = pandas.read_csv('titanic.csv', index_col='PassengerId')
X = data[['Fare', 'Pclass', 'Age', 'Sex', 'Survived']].dropna(axis=0).as_matrix()
X[X[:, 3] == 'female', 3] = 0
X[X[:, 3] == 'male', 3] = 1
survived = X[:, 4].astype(np.int64)
X = np.delete(X, [4], axis=1)



clf = DecisionTreeClassifier(random_state=241)
clf.fit(X, survived)
clf.feature_importances_

array([ 0.30644165,  0.13700004,  0.2560461 ,  0.30051221])

In [3]:
X = data[['Pclass', 'Fare', 'Age', 'Sex', 'Survived']].dropna(axis=0).as_matrix()
X[X[:, 3] == 'female', 3] = 0
X[X[:, 3] == 'male', 3] = 1
print X
print X[3]
data[['Pclass', 'Fare', 'Age', 'Sex', 'Survived']].dropna(axis=0)

[[3 7.25 22.0 1 0]
 [1 71.2833 38.0 0 1]
 [3 7.925 26.0 0 1]
 ...,
 [1 30.0 19.0 0 1]
 [1 30.0 26.0 1 1]
 [3 7.75 32.0 1 0]]
[1 53.1 35.0 0 1]

             Pclass      Fare   Age     Sex  Survived
PassengerId
1                 3    7.2500  22.0    male         0
2                 1   71.2833  38.0  female         1
3                 3    7.9250  26.0  female         1
4                 1   53.1000  35.0  female         1
5                 3    8.0500  35.0    male         0
7                 1   51.8625  54.0    male         0
8                 3   21.0750   2.0    male         0
9                 3   11.1333  27.0  female         1
10                2   30.0708  14.0  female         1
11                3   16.7000   4.0  female         1
12                1   26.5500  58.0  female         1
13                3    8.0500  20.0    male         0
14                3   31.2750  39.0    male         0
15                3    7.8542  14.0  female         0
16                2   16.0000  55.0  female         1
17                3   29.1250   2.0    male         0
19                3   18.0000  31.0  female         0
21                2   26.0000  35.0    male         0
22                2   13.0000  34.0    male         1
23                3    8.0292  15.0  female         1
24                1   35.5000  28.0    male         1
25                3   21.0750   8.0  female         0
26                3   31.3875  38.0  female         1
28                1  263.0000  19.0    male         0
31                1   27.7208  40.0    male         0
34                2   10.5000  66.0    male         0
35                1   82.1708  28.0    male         0
36                1   52.0000  42.0    male         0
38                3    8.0500  21.0    male         0
39                3   18.0000  18.0  female         0
...             ...       ...   ...     ...       ...
857               1  164.8667  45.0  female         1
858               1   26.5500  51.0    male         1
859               3   19.2583  24.0  female         1
861               3   14.1083  41.0    male         0
862               2   11.5000  21.0    male         0
863               1   25.9292  48.0  female         1
865               2   13.0000  24.0    male         0
866               2   13.0000  42.0  female         1
867               2   13.8583  27.0  female         1
868               1   50.4958  31.0    male         0
870               3   11.1333   4.0    male         1
871               3    7.8958  26.0    male         0
872               1   52.5542  47.0  female         1
873               1    5.0000  33.0    male         0
874               3    9.0000  47.0    male         0
875               2   24.0000  28.0  female         1
876               3    7.2250  15.0  female         1
877               3    9.8458  20.0    male         0
878               3    7.8958  19.0    male         0
880               1   83.1583  56.0  female         1
881               2   26.0000  25.0  female         1
882               3    7.8958  33.0    male         0
883               3   10.5167  22.0  female         0
884               2   10.5000  28.0    male         0
885               3    7.0500  25.0    male         0
886               3   29.1250  39.0  female         0
887               2   13.0000  27.0    male         0
888               1   30.0000  19.0  female         1
890               1   30.0000  26.0    male         1
891               3    7.7500  32.0    male         0

[714 rows x 5 columns]